name: Project Linkage
description: Temporary template, pls don't use this 
title: '[TEMP] '
labels: 'test'
projects: "notkaramel/3"
body:
  - type: markdown
    attributes:
      value: |
        **Please describe your issue here**
  - type: textarea
    attributes:
      label: "What's wrong?"


